name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.danielcruzr }}
          password: ${{ secrets.220412S2s }}
      - name: Build e empurre contêiner
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: danielcruzr/streamlit:latest
      - name: Execute o contêiner
        run: |
          docker run -d -p 8080:80 danielcruzr/streamlit:latest
