name: Update Prices
on:
  schedule:
    - cron: '*/1 * * * *' 
  workflow_dispatch:

jobs:
  update_symbol_list:
    name: Update Prices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: |
          python ml_advice_tests.py
